name: Task E - Supply Chain Audit (SBOM)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  generate-sbom:
    name: Build, Scan and Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build local container image
        run: docker build -t temp-target:latest .

      - name: Generate CycloneDX SBOM with Anchore Syft
        uses: anchore/sbom-action@v0
        with:
          image: "temp-target:latest"
          format: "cyclonedx-json"
          output-file: "sbom.json"

      - name: Save SBOM as pipeline artefact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.json

      - name: Scan container image with Aqua Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "temp-target:latest"
          format: "table"
          exit-code: "1"

      - name: Save Trivy vulnerability report as artefact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-vulnerability-report
          path: trivy-report.txt

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Tag and push Docker image to GHCR
        run: |
          docker tag temp-target:latest ghcr.io/sammy-nte/7021scn_task_e:latest
          docker push ghcr.io/sammy-nte/7021scn_task_e:latest